---
- name: Configure bootsrap node for Kubernetes cluster
  hosts: control_plane
  become: true
  vars_files:
    - ../../inventory/production/group_vars/pki.yml

  roles:
    - role: controlplane
      tags: controlplane
