- import_playbook: etcd/site.yml
- import_playbook: loadbalancer/site.yml
- import_playbook: kubernetes/site.yml
- import_playbook: controlplane/bootstrap.yml
- import_playbook: cilium/site.yml
- import_playbook: controlplane/join.yml
