---
- name: Controlplane | Preflight
  ansible.builtin.include_tasks:
    file: preflight.yml

- name: Controlplane | Configure PKI
  ansible.builtin.include_tasks:
    file: pki.yml

- name: Controlplane | Configure kubeadm
  ansible.builtin.include_tasks:
    file: kubeadm_config.yml

- name: Controlplane | Bootstrap cluster
  ansible.builtin.include_tasks:
    file: bootstrap.yml

- name: Controlplane | Validate cluster
  ansible.builtin.include_tasks:
    file: validate.yml
